CREATE TABLE COFFE_HOUSE(
    ID_COFFEHOUSE INTEGER PRIMARY KEY,
    ADDR_COFFEHOUSE VARCHAR(200) NOT NULL,
    VALID_FROM DATE NOT NULL,
    VALID_TO  DATE
);

CREATE TABLE STAFF(
    ID_PERSON INTEGER PRIMARY KEY,
    ID_COFFEHOUSE INTEGER,
    JOB_NAME VARCHAR(100) NOT NULL,
    SALARY INTEGER NOT NULL,
    PERSON_NAME VARCHAR(200) NOT NULL,
    IS_BUSY BOOLEAN NOT NULL,
    FOREIGN KEY (ID_COFFEHOUSE) REFERENCES COFFE_HOUSE(ID_COFFEHOUSE)
);


CREATE TABLE OFFLINE_CLIENTS(
    ID_CLIENT INTEGER PRIMARY KEY,
    ID_WAITER INTEGER,
    PRICE INTEGER NOT NULL,
    ID_COFFEHOUSE INTEGER ,
    FOREIGN KEY (ID_COFFEHOUSE) REFERENCES COFFE_HOUSE(ID_COFFEHOUSE),
    FOREIGN KEY (ID_WAITER) REFERENCES STAFF(ID_PERSON)
);
CREATE TABLE ONLINE_CLIENTS(
    ID_CLIENT INTEGER PRIMARY KEY,
    ID_COURIER INTEGER,
    PRICE INTEGER NOT NULL,
    ID_COFFEHOUSE INTEGER ,
    FOREIGN KEY (ID_COFFEHOUSE) REFERENCES COFFE_HOUSE(ID_COFFEHOUSE),
    FOREIGN KEY (ID_COURIER) REFERENCES STAFF(ID_PERSON)
);

CREATE TABLE DISHES(
    DISH_NAME  VARCHAR(100) PRIMARY KEY,
    PRICE INTEGER NOT NULL
);

CREATE TABLE ONLINE_ORDERS(
    ID_CLIENT INTEGER,
    DISH_NAME VARCHAR(100),
    NUMBER INTEGER NOT NULL,
    PRIMARY KEY(ID_CLIENT, DISH_NAME),
    FOREIGN KEY (ID_CLIENT) REFERENCES ONLINE_CLIENTS(ID_CLIENT),
    FOREIGN KEY (DISH_NAME) REFERENCES DISHES(DISH_NAME)
);

CREATE TABLE OFFLINE_ORDERS(
    ID_CLIENT INTEGER,
    DISH_NAME VARCHAR(100),
    NUMBER INTEGER NOT NULL,
    PRIMARY KEY(ID_CLIENT, DISH_NAME),
    FOREIGN KEY (ID_CLIENT) REFERENCES OFFLINE_CLIENTS(ID_CLIENT),
    FOREIGN KEY (DISH_NAME) REFERENCES DISHES(DISH_NAME)
);


CREATE TABLE SUPPLIERS(
    SUPPLIER_ID INTEGER PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(100) NOT NULL,
    ID_COFFEHOUSE INTEGER,
    FOREIGN KEY (ID_COFFEHOUSE) REFERENCES COFFE_HOUSE(ID_COFFEHOUSE)
);
